FROM golang:1.22-alpine

WORKDIR /app

# Copy go.mod and go.sum and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of your code
COPY . .

EXPOSE 8080

# For development, run the app directly to leverage hot reloading tools
CMD ["go", "run", "main.go"]
