name: GO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go 1.22
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Download Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

      - name: Build Application
        run: go build -v .

      - name: Build Docker Image
        run: docker build -t reflect-therapy-go .
